set(_AMENT_PACKAGE_NAME "tidybot_robot")
set(tidybot_robot_VERSION "0.1.0")
set(tidybot_robot_MAINTAINER "Developer <dev@example.com>")
set(tidybot_robot_BUILD_DEPENDS "rclcpp" "rclpy" "urdf" "xacro" "robot_state_publisher" "joint_state_publisher" "sensor_msgs" "geometry_msgs" "nav_msgs" "tf2" "tf2_ros" "ros_gz_sim" "ros_gz_bridge")
set(tidybot_robot_BUILDTOOL_DEPENDS "ament_cmake")
set(tidybot_robot_BUILD_EXPORT_DEPENDS "rclcpp" "rclpy" "urdf" "xacro" "robot_state_publisher" "joint_state_publisher" "sensor_msgs" "geometry_msgs" "nav_msgs" "tf2" "tf2_ros" "ros_gz_sim" "ros_gz_bridge")
set(tidybot_robot_BUILDTOOL_EXPORT_DEPENDS )
set(tidybot_robot_EXEC_DEPENDS "launch" "launch_ros" "rclcpp" "rclpy" "urdf" "xacro" "robot_state_publisher" "joint_state_publisher" "sensor_msgs" "geometry_msgs" "nav_msgs" "tf2" "tf2_ros" "ros_gz_sim" "ros_gz_bridge")
set(tidybot_robot_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(tidybot_robot_GROUP_DEPENDS )
set(tidybot_robot_MEMBER_OF_GROUPS )
set(tidybot_robot_DEPRECATED "")
set(tidybot_robot_EXPORT_TAGS)
list(APPEND tidybot_robot_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
